name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: lint python files
          uses: github/super-linter@v4
          env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            VALIDATE_PYTHON: true
        - name: lint CHARP files
          uses: github/super-linter@v4
          env:
              VALIDATE_ALL_CODEBASE: true
              DEFAULT_BRANCH: main
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              VALIDATE_CSHARP: true