name: lint

on:
  push:
    branches:
      - main

jobs:
  linter:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: lint python files
          uses: github/super-linter@v4
          env:
            VALIDATE_ALL_CODEBASE: true
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            VALIDATE_PYTHON: true