name: lint

on:
  push:
    branches:
      - main

jobs:
  linter:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install flake8
        - name: Run linters
          run: |
              flake8 . --count --select=E901,E902,E903,F401,F405 --show-source --statistics --exit-zero
