name: readme checker

on:
  push:
    branches:
      - main

jobs:
  readme-checker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: step readme checker
          run: |
              ls -ali; if [ ! -f README.md ]; then 
                echo "Failed: README.md not found."; exit 1; fi